// <auto-generated />
using DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbContexts.Migrations
{
    [DbContext(typeof(DbEasyLife))]
    [Migration("20190410080307_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.YouBikeSite", b =>
                {
                    b.Property<int>("SiteNumber");

                    b.Property<string>("Address");

                    b.Property<string>("Area");

                    b.Property<int>("IdelBikeCount");

                    b.Property<int>("IsActive");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longtitude");

                    b.Property<int>("ParkingSpaceCount");

                    b.Property<string>("SiteName");

                    b.Property<string>("UpdatedAt");

                    b.HasKey("SiteNumber");

                    b.ToTable("YouBikeSites");
                });
#pragma warning restore 612, 618
        }
    }
}
